# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20170429_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
