# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='isStylist',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
