# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_invoice_isstylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transactionId',
            field=models.CharField(max_length=10),
        ),
    ]
