# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_auto_20170418_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutiqueitem',
            options={'ordering': ('name',), 'verbose_name': 'boutiqueitem', 'verbose_name_plural': 'boutique items'},
        ),
    ]
