# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_auto_20170418_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutiqueitem',
            options={'ordering': ('name',), 'verbose_name': 'boutique item', 'verbose_name_plural': 'boutique items'},
        ),
    ]
