# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='invoiceId',
        ),
    ]
