# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_service_stylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
