# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_transaction_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taxRate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'taxes',
                'verbose_name': 'taxes',
            },
        ),
    ]
