# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_taxes_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='taxRate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
