# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=200)),
                ('salon_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retail_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity_in_stock', models.IntegerField(max_length=50)),
                ('min_in_stock', models.IntegerField(max_length=50)),
                ('sku', models.IntegerField(max_length=50)),
                ('size', models.IntegerField(max_length=50)),
                ('pur_date', models.DateTimeField(verbose_name='date purchased')),
                ('employee', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalonItem',
            fields=[
                ('salon_item_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('s_price', models.IntegerField(max_length=50)),
                ('r_price', models.IntegerField(max_length=50)),
                ('purchased_date', models.DateTimeField(verbose_name='date purchased')),
                ('employee', models.CharField(max_length=200)),
            ],
        ),
    ]
