# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique_Items',
            fields=[
                ('boutique_item_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('salon_price', models.IntegerField(max_length=50)),
                ('retail_price', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conditioner',
            fields=[
                ('conditioner_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('salon_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retail_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity_in_stock', models.IntegerField(max_length=50)),
                ('minimum_in_stock', models.IntegerField(max_length=50)),
                ('sku', models.IntegerField(max_length=50)),
                ('size', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shampoo',
            fields=[
                ('shampoo_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('salon_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retail_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity_in_stock', models.IntegerField(max_length=50)),
                ('minimum_in_stock', models.IntegerField(max_length=50)),
                ('sku', models.IntegerField(max_length=50)),
                ('size', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Styling_Products',
            fields=[
                ('styling_product_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('salon_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retail_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity_in_stock', models.IntegerField(max_length=50)),
                ('minimum_in_stock', models.IntegerField(max_length=50)),
                ('sku', models.IntegerField(max_length=50)),
                ('size', models.IntegerField(max_length=50)),
            ],
        ),
    ]
