# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('stylist_first_name', models.CharField(max_length=200, primary_key=True)),
                ('stylist_last_name', models.CharField(default='', max_length=200, serialize=False)),
                ('stylist_description', models.CharField(max_length=500)),
            ],
        ),
    ]
