# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20170328_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='stylist_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='stylist',
            old_name='stylist_last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='stylist_first_name',
        ),
        migrations.AddField(
            model_name='stylist',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
