# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
    ]
