# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170328_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
