# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_auto_20170418_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to='salon.Category')),
            ],
            options={
                'verbose_name_plural': 'boutiques',
                'verbose_name': 'boutique',
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='boutiqueitem',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='boutiqueitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='BoutiqueItem',
        ),
        migrations.AlterIndexTogether(
            name='boutique',
            index_together=set([('id', 'slug')]),
        ),
    ]
