# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_auto_20170418_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('service',),
            },
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'stylist',
                'verbose_name_plural': 'stylists',
                'ordering': ('name',),
            },
        ),
    ]
